# Generated by Django 6.0.7 on 2026-08-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_institute_alter_user_role_user_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('BASIC', 'Basic Plan'), ('PROFESSIONAL', 'Professional Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='FREE_TRIAL', max_length=20, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_students', models.IntegerField(default=50)),
                ('max_staff', models.IntegerField(default=10)),
                ('ai_credits_monthly', models.IntegerField(default=100)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='academic_year',
            field=models.CharField(default='2026-2027', max_length=20),
        ),
        migrations.AddField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='institute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='institute',
            name='subscription_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('ADMIN', 'Institute Admin'), ('TRAINER', 'Staff / Trainer'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('RECEPTION_HR', 'Reception / HR')], default='STUDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='institute',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionplan'),
        ),
    ]
