# Generated by Django 6.0.7 on 2026-08-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='geofence_radius_meters',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='institute',
            name='latitude',
            field=models.FloatField(default=9.9312),
        ),
        migrations.AddField(
            model_name='institute',
            name='longitude',
            field=models.FloatField(default=76.2673),
        ),
    ]
