# Generated by Django 6.0.7 on 2026-08-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_subscriptionplan_institute_academic_year_and_more'),
        ('courses', '0002_course_institute_alter_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('MCQ', 'Multiple Choice Test'), ('CODING', 'Coding Challenge'), ('PRACTICAL', 'Practical Lab Assessment')], default='MCQ', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=40)),
                ('scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='courses.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.institute')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='examinations.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option', models.IntegerField(default=0)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('test_cases', models.JSONField(blank=True, default=list)),
                ('marks', models.IntegerField(default=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.exam')),
            ],
        ),
    ]
