# Generated by Django 6.0.7 on 2026-08-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_subscriptionplan_institute_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('interested_course', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website Enquiry'), ('WALK_IN', 'Walk-in Visit'), ('REFERRAL', 'Student Referral'), ('SOCIAL', 'Social Media'), ('CALL', 'Phone Call')], default='WEBSITE', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('CONTACTED', 'Contacted'), ('COUNSELED', 'Counseled'), ('REGISTERED', 'Onboarded'), ('LOST', 'Closed / Lost')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='accounts.institute')),
            ],
        ),
    ]
