# Generated by Django 6.0.7 on 2026-08-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_subscriptionplan_institute_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.institute')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('role_description', models.TextField()),
                ('package_lpa', models.DecimalField(decimal_places=2, default=6.5, max_digits=5)),
                ('eligibility_criteria', models.CharField(default='Minimum 75% Attendance & Passing Grades', max_length=200)),
                ('drive_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placements.company')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='accounts.institute')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWED', 'Interview Scheduled'), ('SELECTED', 'Selected / Offered'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('offer_letter_url', models.URLField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placementdrive')),
            ],
        ),
    ]
