# Generated by Django 6.0.7 on 2026-08-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_subscriptionplan_institute_academic_year_and_more'),
        ('courses', '0002_course_institute_alter_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('COMPLETION', 'Course Completion Certificate'), ('INTERNSHIP', 'Internship Certificate'), ('WORKSHOP', 'Workshop Certificate')], default='COMPLETION', max_length=20)),
                ('verification_code', models.CharField(max_length=64, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
